# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# trigger:
#   branches:
#     include:
#     - main
#   paths:
#     exclude:
#     - README.md
#     - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ado-arm-connection'
    ScriptType: 'FilePath'
    ScriptPath: './deploy.ps1'
    azurePowerShellVersion: 'LatestVersion'
